server:
  port: 8080
  name: "Body Mass Menager"

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_CONNECTION_STRING}





